### ISSUE TITLE
SMTPSecure configuration

### ISSUE THREAD

**Issue by wpf500** [soup-bowl/wp-simple-smtp#11]
Hello! Firstly thanks for this plugin, much nicer than all the bloat of WP Mail SMTP etc.

One little problem we've had is that we need to be able to set the `SMTPSecure` setting on the `PHPMailer` instance for authentication to work. For now I've hacked the following in below line 83 in `class-mail.php`
```php
$phpmailer->SMTPSecure = 'ssl';
```

I believe the value of `SMTPSecure` can be `ssl` or `tls` but I haven't really looked into it.

It would be great if this was configurable, we use the `wp-config.php` defines but I guess it should be a UI option too. I'm happy to try to submit a PR when I find a moment if that is useful?

**Comment by soup-bowl** [comment]
Hello! 👋 I'm glad to hear you've been able to find some use in this plugin!

Ah, I've mistakenly assumed that PHPMailer's SMTPSecure option is an automated configuration when left on default. I can see I've missed quite a lot of use cases in doing so. Thank you for pointing this out!

It's okay, I'm happy to add this in (both environmental and config file). I'll add this as a task and implement it in the next release.

**Comment by wpf500** [comment]
Thanks!
