### ISSUE TITLE
Add dashboard widget

### ISSUE THREAD

**Issue by kebbet** [soup-bowl/wp-simple-smtp#110]
Something like this? WIP.

Is this needed, a nice to have? What info should be displayed?
Maybe a counter of total amount of e-mails sent, decoupled from log entries?

<img width="453" alt="bild" src="https://user-images.githubusercontent.com/11491369/162616382-01c9b318-7af4-4fff-a6d4-7c550805beae.png">

**Comment by soup-bowl** [comment]
I'd be more keen to poll this to see if this would be a general desire to add. My experience with WordPress has typically been that there's so much dashboard spam that I generally dislike plugins that add spurious widgets. I'm aware you can turn them off, but they're normally enabled by default.

**Comment by soup-bowl** [comment]
Feel like for a simple SMTP plugin, the little indicator in the glance widget is enough of a dashboard involvement. Of course community might have different opinion on this.

**Comment by kebbet** [comment]
I agree, maybe not suited for a simple plugin like this.

**Comment by soup-bowl** [comment]
> I agree, maybe not suited for a simple plugin like this.

The plugin is open licensed, so if you want to take the direction of a more feature-rich direction you are more than welcome to make a derivative. If you do, keep it as a fork so you can pull forward fixes that get applied here :smile:
