### ISSUE TITLE
Test against WordPress 6.0 (before 2022/05/24)

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#112]
[WordPress 6.0](https://make.wordpress.org/core/6-0/) is due for release **24th May 2022**. Any comments confirming working on a test 6.0 system are appreciated, and any detailed debug logs and/or reproduction steps if it has failed.

[Latest changes in Core ](https://github.com/WordPress/WordPress/blob/master/wp-includes/PHPMailer/PHPMailer.php) appear to be to upgrade the library to **PHPMailer 6.6.0**.

**Comment by kebbet** [comment]
Seems to work with 6.0 RC3. Sends e-mails, logs them. Can remove them and re-send them.
