### ISSUE TITLE
Extra headers not stored in log?

### ISSUE THREAD

**Issue by kebbet** [soup-bowl/wp-simple-smtp#113]
**What WordPress, PHP and Simple SMTP versions are you using?**
e.g. WordPress 5.9.3, PHP 7.3, Simple SMTP 1.3.1.

**Describe the bug**
When adding custom headers to email, they are not stored in the log entry. Use case is:
- Adding CC-header for custom cron debug e-mails.

**Steps to reproduce**

- Create custom function that uses `wp_mail`.
- Set a CC-header like `$headers[] = 'Cc: Name <want-debug-info@wpsimplesmtp.com>';`
- Recieve e-mail, with headers present
- See log table and log entry: it's missing the CC-header data.

**Expected behavior**
I expected CC and BCC-headers present in log information.

**Screenshots**

**Comment by soup-bowl** [comment]
I've tried this on my machine and the CC is still present. WordPress pushes CC, BCC, etc into the headers, which are stored in the log but not displayed on the log table.

I've tried it on my dev, added CC to test email, sent it, resent email, edited the last one CC and resent - all came through fine.
