### ISSUE TITLE
Fatal error when Sucuri Scanner is installed

### ISSUE THREAD

**Issue by benoitchantre** [soup-bowl/wp-simple-smtp#115]
**What WordPress, PHP and Simple SMTP versions are you using?**
- WordPress 5.8.3
- Simple SMTP 1.3.1

**Describe the bug**
Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting!

**Steps to reproduce**
1. Install [Sucuri Scanner](https://wordpress.org/plugins/sucuri-scanner/)
2. Install Simple SMTP
3. Send a test email

**Expected behavior**
The test email shoud be sent.

**Comment by benoitchantre** [comment]
To prevent this error, I had to stop alerts for the post type `sbss_email_log` in Sucuri Scanner settings or disable _Receive email alerts for changes in the post status (configure from Ignore Posts Changes)_.

**Comment by soup-bowl** [comment]
Great, it detects the CPT of the email log and notifies by default that something has changed, thereby initiating an infinite logic loop of it detecting a change, sending an email, detecting a change, etc etc etc until PHP crashes... At least that's how it worked on my test machine.

**Comment by soup-bowl** [comment]
```php
// Patch fix to stop Sucuri from spamming the log. Should be investigated more.
$dup_check = post_exists( $log->get_subject(), '', current_time( 'mysql' ), $this->post_type );
if ( 0 !== $dup_check ) {
	return $dup_check;
}
```
This added to line 63 (underneath `public function new_log_entry( $log ) {`) catches the rampant logging on my side. I'm going to do a few more tests and add it to the next release if it works. If you've got a dev environment of the affected site, a confirmation would be appreciated.

**Comment by benoitchantre** [comment]
Thank you, I'll do some tests and let you know

**Comment by soup-bowl** [comment]
To be clear: It will still write 1-2 notification entries in the log after an email is sent, but this 'patch' will stop it writing them indefinitely. I think that's the best approach I can take from this plugin side without re-writing the logging code.

**Comment by benoitchantre** [comment]
Unfortunately, there's no filter available in Sucuri Scanner to programmatically ignore status changes for the `sbss_email_log` post type.

**Comment by soup-bowl** [comment]
> Unfortunately, there's no filter available in Sucuri Scanner to programmatically ignore status changes for the `sbss_email_log` post type.

Thanks, I think I'll reach out to the developers anyway to discuss it. I'm not a primary WP dev anymore so I'll ask them in case there's something I've missed. Either way, this patch should stop the runaway generations at least.

**Comment by soup-bowl** [comment]
Re-opening this issue - due to a major bug the #116 PR triggered, this has been reverted.

If this was working for you, I recommend not upgrading to 1.3.2.1.

**Comment by benoitchantre** [comment]
> Re-opening this issue - due to a major bug the #116 PR triggered, this has been reverted.
> 
> If this was working for you, I recommend not upgrading to 1.3.2.1.

Thank you for the note.

I have finally build a mu-plugin with the required filters instead of this plugin because of #121.

**Comment by soup-bowl** [comment]
Nice - glad to hear you made a solution that works better for you. In that case you can unsubscribe on the right hand side so you don’t get pestered with updates that are now irrelevant.

**Comment by soup-bowl** [comment]
Added a warning about plugin incompatibility to the plugin readme.
