### ISSUE TITLE
Show headers in email log view

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#118]
Based on a debugging session of #113, it's noticeable that the headers kept by the log aren't shown in the log view. Alongside it making debugging harder, it would also likely benefit the user since it contains CC, BCC and so on.

It might be good to add headers to the log view. I think adding them to the log *table* would be too much.

**Comment by kebbet** [comment]
Agree on log view, and not table..

But to test, icons/markers could be added to the table. Like the mockup below..

<img width="778" alt="bild" src="https://user-images.githubusercontent.com/11491369/168750697-68aa18cc-7564-4f84-ad11-7b820f3af790.png">

**Comment by soup-bowl** [comment]
The recipients column could be adjusted so it combines the two aspects - it shows the recipients with badges for to, cc and bcc. It might add some overhead to the load as it will need to check the recipients in the headers as well as to (seems WP was built to expect emails to be sent _to_ someone but not so much to be cc'ed).

I'll experiment with some options. Also be good to know a selection of plugins that are sending emails via different methods so I can run some tests.
