### ISSUE TITLE
Log posts shows up as ”Posts” in WordPress export view.

### ISSUE THREAD

**Issue by kebbet** [soup-bowl/wp-simple-smtp#122]
**What WordPress, PHP and Simple SMTP versions are you using?**
WP 6.0, plugin 1.3.1.1

**Describe the bug**
Log posts are displayed as ”Posts” in the export view. This is confusing. Should be ”E-mail log posts” or similar.

**Steps to reproduce**
1. Go to 'wp-admin/export.php'
2. See multiple 'Posts'

**Expected behavior**
Another name of the post type.

**Screenshots**

**Comment by kebbet** [comment]
Add this to `class-logservice.php` on line 52
```
				'label'        => __( 'E-mail log entries', 'wp-simple-smtp' ),
```

**Comment by kebbet** [comment]
After
<img width="782" alt="bild" src="https://user-images.githubusercontent.com/11491369/171256167-bcfa2991-4667-4f8d-ad18-0142a9fda38d.png">

**Comment by soup-bowl** [comment]
I've removed my assignation - feel free to make a PR on this.

**Comment by kebbet** [comment]
Upcoming!
