### ISSUE TITLE
Fatal error: Call to undefined function wpsimplesmtp\post_exists()

### ISSUE THREAD

**Issue by huubl** [soup-bowl/wp-simple-smtp#128]
**What WordPress, PHP and Simple SMTP versions are you using?**
WordPress 6.0.2
PHP 8.0.16
Simple SMTP 1.3.2
Gravity Forms 2.6.7
[Bedrock setup](https://github.com/roots/bedrock) 

**Describe the bug**
Fatal 500 error when trying to submit a form (Gravity Forms):

[simple-smtp/src/log/class-logservice.php (line 65)](https://github.com/soup-bowl/wp-simple-smtp/blob/0a9b6bb0632b491f2acb4dc843a1fbbcff73e4d5/src/log/class-logservice.php#L65)
```
Call to undefined function wpsimplesmtp\post_exists()
```

It seems it has something to do with the namespacing. I tried changing it to the global space:
`$dup_check = \post_exists( $log->get_subject(), '', current_time( 'mysql' ), $this->post_type );`

Unfortunately I still get the similar error: `Call to undefined function post_exists()`

**Steps to reproduce**
Enable debug and use setup from above.

**Expected behavior**
No errors :)

**Screenshots**

![image](https://user-images.githubusercontent.com/50170696/195301662-8c024791-1b44-40db-b5d8-b1acfe7bcbae.png)

**Comment by soup-bowl** [comment]
In theory it should be fine as a lot of the WordPress functions are available in that method. I'll have a look as a priority when I'm next available, for now you can comment out the lines 65-68 to stop the system from throwing a 500, or downgrade back to 1.3.1.1.

Thanks for linking directly to the line of code - very helpful.

**Comment by soup-bowl** [comment]
Tested this in the standard use-case (normal WP install) and it works fine. It might be being caused by Bedrock? It's the first I've seen it, so I'll have to give it a proper look.

**Comment by soup-bowl** [comment]
Kebbet has come across a similar bug in #130.

In both situations - for an urgent fix I would suggest downgrading the plugin. Thankfully I can replicate this issue now so I can look into it.

**Comment by kebbet** [comment]
Ah! Stumbled upon this when a user tried to set it's password on a site a couple of days ago, forgot to dig into it then.

<img width="770" alt="bild" src="https://user-images.githubusercontent.com/11491369/196529109-8fd98e84-0a9d-4c34-a544-ef13c2f15782.png">

**Comment by kebbet** [comment]
> Yep, it seems like `post_exists` is not available in a non-administrative context. double-checked the documentation and I can't see it mentioned.
> 
> https://developer.wordpress.org/reference/functions/post_exists/ https://wordpress.stackexchange.com/questions/218715/fatal-error-call-to-undefined-function-post-exists
> 
> I did a manual test before release, I'm not 100% clear why this wasn't picked up. Nor was I able to replicate it via Ninja Forms. Perhaps they execute in different contexts.

Did you see this comment, I was thinking the same with the folder `wp-admin/`
https://wordpress.stackexchange.com/a/218783

**Comment by soup-bowl** [comment]
Yes - it forms part of the testing I'll do before issuing a hotfix. I'm pretty sure the email function will execute outside of admin context, so the 2nd option would 'fix' it, but I'm not keen on modifying the scope to add some additional functions as this could cause problems with other plugins.

I'll investigate, but I'd rather say the plugin is incompatible with plugins that interfere with the log post-type, than to spend lots of time writing the mailcheck and delaying the fix, or adjusting the global function scope outside of WP standard.

**Comment by soup-bowl** [comment]
I've pushed 1.3.2.1 - a patch fix to remove this. The latest version should now no longer suffer from this.
