### ISSUE TITLE
WordPress 6.2 Verification

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#139]
[WordPress 6.2](https://make.wordpress.org/core/2023/03/09/wordpress-6-2-field-guide/) is due to be released **March 28th, 2023** (deadline missed). Readme needs to be updated to reflect compatibility after a full-cycle test.

[PHPMailer](https://github.com/WordPress/WordPress/blob/master/wp-includes/PHPMailer/PHPMailer.php) appears to be **6.8.0**

**Comment by kebbet** [comment]
Plugin seems to work just like before `6.2`, running both multisite and single site installations.
