### ISSUE TITLE
unexpected 'list' (T_LIST), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by medicamin** [soup-bowl/wp-simple-smtp#140]
**What WordPress, PHP and Simple SMTP versions are you using?**
WordPress 6.1, PHP 7.4, Simple SMTP 1.3.2.1

**Describe the bug**
I see this error in my error logs:
Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /home/***/public_html/wp-content/plugins/simple-smtp/src/cli/class-emaillog.php on line 112

The plugin works great, but I get this error in logs.

**Comment by soup-bowl** [comment]
I seem to run afoul of conflicting with the [inbuilt list](https://www.php.net/manual/en/function.list.php) function in the WordPress CLI functionality. Thanks for reporting this. I'll fix this in the next release.

Interesting this has never flagged before (and my Gitpod environment doesn't flag it either) - are you running PHP in debug mode?
