### ISSUE TITLE
SMTP Error: Could not connect to SMTP host. STARTTLS command failed TLS not available due to local problem 

### ISSUE THREAD

**Issue by davelozier** [soup-bowl/wp-simple-smtp#148]
### What WordPress, PHP and Simple SMTP versions are you using?

Wordpress 6.3.1, PHP 7.4.30, Simple SMTP 1.3.2.2

### What were you doing when the bug occurred?

We have postfix on our local network in a "send only" setup.  There is no encryption in use. 

Easy WP SMTP functions but we'd like to move away from this plugin.

### What was the result you expected?

Test email sent without issue.

**Comment by davelozier** [comment]
For a temp solution I modified process_mail() and added the following:

`$phpmailer->SMTPAutoTLS = false;`

This works as expected now.

**Comment by soup-bowl** [comment]
I'll look at adding a "None" option to the encryption type.

Weird, I seem to remember us using this plugin in early forms for years on an unauthenticated SMTP server and it worked alright. I need to see if the SSL enforcement is breaking the auto-detection.

**Comment by davelozier** [comment]
Thank you! This plugin is our go-to solution now for wordpress/smtp. Clean, simple and elegant..
