### ISSUE TITLE
Multisite site admins can see email password

### ISSUE THREAD

**Issue by nepse1** [soup-bowl/wp-simple-smtp#61]
**What WordPress, PHP and Simple SMTP versions are you using?**
e.g. WordPress 5.6, PHP 7.3, Simple SMTP 1.0.0. The more, the better.
Newest, upgraded.

**Describe the bug**
Multisite site admins can see email password in plain HTML.

**Steps to reproduce**
1. Log in as site admin in WP multisite install
2. go to subsite mail settings page: /wp-admin/options-general.php?page=wpsimplesmtp
3. Inspect source (view HTML)
4. See password in clear text as input value=""

**Expected behavior**
Password is already stored in database, and site admin mail settings is greyed out - no need to fill input fields.

**Screenshots**

**Comment by soup-bowl** [comment]
Discovered a bug in the development build that causes the system to fail when a multisite password is set.

> Could not instantiate mail function.

**Comment by soup-bowl** [comment]
Bug actually relates to a different system aspect semi-unrelated to this.
