### ISSUE TITLE
GitHub-based installation support

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#69]
There's a growing trend with some sites to install plugins found on open development platforms instead of via the WordPress plugin site. I have no plans to stop the Codex variant of the plugin, but with a minor change to the plugin file & CI/CD process it should be possible to provide builds via this GitHub repository alongside the WordPress plugin store.

There's two Git-based plugin installers - [Afragen's](https://github.com/afragen/git-updater) and [Radishconcepts](https://github.com/radishconcepts/WordPress-GitHub-Plugin-Updater) - that I'm aware of that can have supported baked in. I can adjust the pipeline to drop a zip copy of the plugin into the release directory, which should then (ideally? Need to read up) pick up in the updater processes.

**Comment by benoitchantre** [comment]
I’m curious to know why someone would install a plug-in from GitHub when it’s already available from the wp.org repository. What would be the benefits? My guess is that you can rollback to a previous version if needed, but you can do that with WP-CLI.

I have already used GitHub updated in the past, but only for repositories that were not published to the wp.org repository. Mostly for private repositories.

**Comment by soup-bowl** [comment]
GitHub might be a partial misnomer here, but generally speaking from my experience some people like to keep their plugins on privately hosted repositories, and then begin to extend this to keeping custom repositories for their approved plugins. True in some big organisations that have their own "approvals" systems before allowing plugins to be rolled into independent productions. This will mostly help that along, but also serves for me as a bit of a learning experience.

Another reason is some people have agreement differences with the WordPress ecosystem, so prefer to use plugins hosted on open platforms rather than through WordPress. I don't share said disagreements, but helps to broaden horizons nonetheless. GitHub is a great distribution platform in this regard, without having to extend to even more plugin hosts like ClassicPress.

And for me personal mantra: because we can :smile: adds a big feature by literally adding a few lines.
