### ISSUE TITLE
Logs are kept when the plugin is uninstalled

### ISSUE THREAD

**Issue by benoitchantre** [soup-bowl/wp-simple-smtp#70]
**What WordPress, PHP and Simple SMTP versions are you using?**

- WordPress 5.8.2
- Simple SMTP 1.2.3

**Describe the bug**
I have noticed the logs are still in the database after having uninstalled the plugin

**Steps to reproduce**
1. Enable logs
2. Send some emails
3. Disable and remove the plugin
4. Reinstall the plugin
5. Look at the logs

**Expected behavior**
All plugin data, including logs should be deleted.

**Comment by soup-bowl** [comment]
Note from ticket #71 - Also execute procedure upon toggling off the logging functionality.
