### ISSUE TITLE
Automatically delete logs after some time

### ISSUE THREAD

**Issue by benoitchantre** [soup-bowl/wp-simple-smtp#71]
It would be awesome to have a cron job to automatically delete logged emails after a specific amount of time

**Comment by soup-bowl** [comment]
I like this idea, good suggestion! I've noticed one of our sites has amassed up to 50 pages of logs and you can be sure that will never get looked at.

Since the capacity is already there for audit integration, I think I'll look into adding it as a filter override for now.

**Comment by benoitchantre** [comment]
Thank you for your feedback. I think a default value of two weeks should be enough for common use cases and GDPR friendly.

Also, when we disable email logs, I think the logs should be cleared.

**Comment by soup-bowl** [comment]
> Also, when we disable email logs, I think the logs should be cleared.
I envisioned that under #70, as disabling the logs should effectively run the same procedure.
