### ISSUE TITLE
Remove unneeded files from release

### ISSUE THREAD

**Issue by benoitchantre** [soup-bowl/wp-simple-smtp#72]
**What WordPress, PHP and Simple SMTP versions are you using?**
Simple SMTP version 1.2.3

**Describe the bug**
The following files should not be part of a release
- `.distignore`
- `package.json`
- `package.lock`

**Comment by soup-bowl** [comment]
Is there a particular reason for dumping the `composer.json/lock` files outside of just executional redundancy? I've personally felt they're worth keeping alongside the codebase as an indicator into some of the less visible functionality of the plugin, but if there's a concern for security I've overlooked I'll happily reconsider.

**Comment by benoitchantre** [comment]
I see no security risk, but as these files are not needed to install or to run the plugin, I suggest to remove them.

**Comment by benoitchantre** [comment]
> they're worth keeping alongside the codebase as an indicator into some of the less visible functionality of the plugin

Looking again at the ˋcomposer.json` file, I don’t understand what do you mean. What functionality? Are you referring to the autoloading process?

**Comment by soup-bowl** [comment]
Trying to recall, my view was that in events of the repository being separated from the codebase, it still means the codebase autoload can still be managed by Composer. The rest of the files expunged by the process are relating to testing or CI/CD processes. Weird thing to consider, but I can't remember the more defined reason or why I was concerned about it.

I think the hang-up was to test it won't effect deployment, but my availability has been spotty to verify it and focus was on getitng the push through to verify 5.9.

**Comment by soup-bowl** [comment]
Some missed info: I had another plugin that I removed Composer files for and it deployed w/o applying Composer. Highly likely to be unrelated, but for lack of better phrasing it gave me the chills on the idea.

**Comment by benoitchantre** [comment]
Composer files are not need for a regular WordPress installation as long as you version control the `vendor` directory in SVN.

If you want to keep it compatible with a Composer managed website (outside of wpackagist), `composer.json` is needed and `composer.lock` can be removed. `composer.json` should contain a `type` property with a value of `wordpress-plugin`.

**Comment by soup-bowl** [comment]
> Composer files are not need for a regular WordPress installation as long as you version control the `vendor` directory in SVN.

I'm aware of this.

> If you want to keep it compatible with a Composer managed website (outside of wpackagist), `composer.json` is needed and `composer.lock` can be removed. `composer.json` should contain a `type` property with a value of `wordpress-plugin`.

Interesting, first I'm hearing about a "Composer managed website". Will have a look into this.

**Comment by benoitchantre** [comment]
A great ressource: https://composer.rarst.net/

**Comment by benoitchantre** [comment]
If you are interested, I can share with you my composer based template for WordPress. Would be happy to have an external feedbacks on that. I can give you more info on Twitter.

**Comment by soup-bowl** [comment]
> If you are interested, I can share with you my composer based template for WordPress. Would be happy to have an external feedbacks on that. I can give you more info on Twitter.

Sounds good to me! Would love to see this, it's a completely new way of WordPress to me that I've never known of before.

(just to say I might have to take some time in reviewing, currently undergoing some huge changes in my personal circumastances at the moment).

**Comment by soup-bowl** [comment]
On review, can now see why it's pointless to keep them in, as it's removing them post-deployment process. For some reason I intially thought this would remove them from the process (I might be thinking of a `.dockerignore` file).
