### ISSUE TITLE
Custom post type to store logs uses default capability type

### ISSUE THREAD

**Issue by benoitchantre** [soup-bowl/wp-simple-smtp#74]
**What WordPress, PHP and Simple SMTP versions are you using?**
Simple SMTP 1.2.3

**Describe the bug**
The custom post type to store logs uses default capability type with no additional capabilities.

**Expected behavior**
The capability required to view/delete logs should be related to an admin role, for example `manage_options`.

**Comment by soup-bowl** [comment]
Good catch on the lazy implementation there. Ironically comes at a time where in a private repo I'm a member of, someone has complained about developers using misguided cap types impacting custom role assignments.

**Comment by benoitchantre** [comment]
#75 is not directly related to this issue.

When the `sbss_email_log` post type is registered, the [default capabilities](https://developer.wordpress.org/reference/functions/register_post_type/#capabilities) (post) are used instead of a capability specific to an adminstrator role.

https://github.com/soup-bowl/wp-simple-smtp/blob/f657d940a742fc8766f887910aa63f06af0c6f65/src/log/class-logservice.php#L38-L40

There shoud be an additional `capabilities` argument passed to this function to be safer.

For example:
```
'capabilities'        => array(
	'publish_posts'       => 'manage_options',
	'edit_others_posts'   => 'manage_options',
	'delete_posts'        => 'manage_options',
	'delete_others_posts' => 'manage_options',
	'read_private_posts'  => 'manage_options',
	'edit_post'           => 'manage_options',
	'delete_post'         => 'manage_options',
	'read_post'           => 'manage_options',
),
```

**Comment by soup-bowl** [comment]
Okay, thanks for clarifying.
