### ISSUE TITLE
Quick settings no longer loading

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#78]
The SMTP quick selection dropdown has vanished.

The cause of this is that my server (soupbowl.io) has undergone a CMS change, and in the process this has blindly broken the password selector. The endpoint is no longer available.

Options are:
1. Provide a new endpoint for the option selector.
2. Remove entirely based on usage (personally discovered this to be more of a hinderance than any actual benefit).

Essential plugin functionality not impacted.

**Comment by benoitchantre** [comment]
Is there a reason that prevent to fetch `source.json` directly from GitHub?
This file can be managed with Pull Request and it's syntax could be automatically checked with Github Actions.

**Comment by soup-bowl** [comment]
Unless there's a concern for security, it could be rolled-in to the plugin entirely. The endpoint suggestions don't change a lot (haven't changed at all since the plugin was made).

**Comment by benoitchantre** [comment]
> The endpoint suggestions don't change a lot (haven't changed at all since the plugin was made).

Based on that, I think it's better to simplify the logic and to keep that data directly in the plugin.
