### ISSUE TITLE
WordPress Plugin Directory doc error - FAQ "How do I stop the logs from automatically purging?"

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#87]
The code segment recommendation for disabling the log auto-delete does not render correctly post-md.

![Instead of a code block surrounding a line of code, the code box contains a backtick with the actual code segment appearing below](https://user-images.githubusercontent.com/11209477/150687109-7b03f1ab-2e2c-4cb8-a514-70eeb9125349.png)

**Comment by soup-bowl** [comment]
I don't understand, the triple-backtick wrap is markdown standard for a [fenced code block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks). Does WordPress not support this?

**Comment by benoitchantre** [comment]
You can render a code block using a simple backtick-wrap instead of a triple backtick-wrap.

**Comment by soup-bowl** [comment]
> You can render a code block using a simple backtick-wrap instead of a triple backtick-wrap.

You're right, and it's [already in-use on the page](https://github.com/soup-bowl/wp-simple-smtp/blob/8db7b2e931cb55bf350e7819721b45bbc94915e7/readme.txt#L23). Will take a look, but my preference would've been a full block.

Noticed their [plugin readme documentation](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#markdown) mentions it uses **Daring Fireball** flavour markdown, and docs don't indicate it supports backtick block but [does support indent](https://daringfireball.net/projects/markdown/syntax#precode). Will verify at some point later (and found some helpful chap has made a [readme validator](https://wpreadme.com/)).

**Comment by benoitchantre** [comment]
> Although it previously worked, code blocks are not supposed to be surrounded by a single backtick, instead according to the [Markdown syntax](https://daringfireball.net/projects/markdown/syntax#precode) they're supposed to be indented (ie. see how [github](https://gist.github.com/dd32/a0cc0bf2fcbb9931f3d573032cada012) parses that readme)
> 
> We're using [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/) which adds extra syntaxes, such as [fenced code blocks](https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks) which should help here.

Source : https://meta.trac.wordpress.org/ticket/2655 (5 years old)

**Comment by kebbet** [comment]
FWIW: Loop-back to this closed issue, just found out how this can be made with back-ticks.

https://wordpress.org/plugins/simple-page-ordering/
https://wordpress.org/plugins/simple-page-ordering/#how%20can%20i%20exclude%20certain%20custom%20post%20types%3F
https://github.com/10up/simple-page-ordering/blob/develop/readme.txt#L81
