### ISSUE TITLE
vendor/autoload.php missing?

### ISSUE THREAD

**Issue by kebbet** [soup-bowl/wp-simple-smtp#97]
**What WordPress, PHP and Simple SMTP versions are you using?**
develop branch

**Describe the bug**
Can not activate plugin in dev environment. What am I missing?

**Steps to reproduce**
1. run `docker compose up`
2. Set up WP.
3. Go to Plugins
4. Try to activate the SImple SMTP-plugin.
5. See error message 
```
Warning: require_once(/var/www/html/wp-content/plugins/simple-smtp/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/simple-smtp/wp-simple-smtp.php on line 32 Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/plugins/simple-smtp/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/simple-smtp/wp-simple-smtp.php on line 32 
```

**Expected behavior**
Thought the plugin could be activated.

**Screenshots**
<img width="1097" alt="bild" src="https://user-images.githubusercontent.com/11491369/157838407-81eacc12-baa8-428b-94c3-077e192e44a6.png">

**Comment by soup-bowl** [comment]
The Docker Compose doesn't currently auto-inject dependencies, last time I tried such a solution it was a three way trade off between filesystem permissions, debugging access and adjustability.

You can run this in the project root to install dependencies w/o installing Composer (from the .gitpod.yml file):

```
docker run --rm --tty --volume $PWD:/app --user $(id -u):$(id -g) composer install --ignore-platform-reqs
```

I Need to set one up for the unit tests too.

**Comment by kebbet** [comment]
Thanks, that worked!
